# Generated by Django 2.2.14 on 2021-02-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
